# Generated by Django 4.1.2 on 2022-10-11 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='usage_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='discount',
            name='usage_max',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
