# Generated by Django 4.1.2 on 2022-10-11 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0002_discount_usage_count_discount_usage_max'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='usage_max',
            field=models.IntegerField(default=0),
        ),
    ]
